# Generated by Django 6.0.1 on 2026-01-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_password_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for the offer', max_length=200)),
                ('message', models.TextField(help_text='The scrolling message text')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority offers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seasonal Offer',
                'verbose_name_plural': 'Seasonal Offers',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
