# Generated by Django 6.0.1 on 2026-01-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or about me'),
        ),
    ]
