# Generated by Django 6.0.1 on 2026-02-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assessment_certificate_payment_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
